### ISSUE TITLE
"rightaway" dialog it's lacking its connections to its signals

### ISSUE THREAD

**Issue by kurinoku** [rakugoteam/Rakugo-The-Question#21]
"book" and "game" signals are not connected to "_on_rightaway_book" and "_on_rightaway_game" respectively.

**Comment by jebedaia360** [comment]
O thanks @kurinoku I must to remove it by accident.
I will fix it soon

**Comment by jebedaia360** [comment]
Fixed in #22 also I added you, @kurinoku to special thanks in credits.
